# Permalinks
permalink:        pretty
collections:
  chapters:
    output: true
  library:
    output: true
  drafts:
    output: true        

defaults:
  - scope:
      path: "/library/"
    values:
      layout: "libraryitem"    